ULTRASONIC_GPIO_TRIGGER = 14
ULTRASONIC_GPIO_ECHO = 4
BUZZER_GPIO = 15

LED_FRONT_DISPLAY_SCLK = 8
LED_FRONT_DISPLAY_DIO  = 9 


RIGHT_LANE_SENSOR = 17
MIDDLE_LANE_SENSOR = 18
LEFT_LANE_SENSOR = 19


VERTICAL_CAMERA_SERVO = 5
HORIZENTAL_CAMERA_SERVO = 6
